services:
  sadtalker:
    build: .
    container_name: echo-sadtalker
    ports:
      - "7862:7862"
    volumes:
      - /volume1/docker/ECHO/data/sadtalker/checkpoints:/app/checkpoints
      - /volume1/docker/ECHO/data/sadtalker/gfpgan_weights:/app/gfpgan/weights
      - /volume1/docker/ECHO/data/sadtalker/results:/app/results
    restart: unless-stopped
